[19/Oct/2015 09:36:27] INFO [apps.hello.views:26] <QueryDict: {}>
[19/Oct/2015 09:36:30] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'0']}>
[19/Oct/2015 09:36:30] ERROR [apps.hello.views:35] 'WSGIRequest' object has no attribute 'new_count'
[19/Oct/2015 09:36:30] INFO [apps.hello.views:36] check requests:{'result': "'WSGIRequest' object has no attribute 'new_count'"}
[19/Oct/2015 09:36:30] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:32] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'0']}>
[19/Oct/2015 09:36:32] ERROR [apps.hello.views:35] 'WSGIRequest' object has no attribute 'new_count'
[19/Oct/2015 09:36:32] INFO [apps.hello.views:36] check requests:{'result': "'WSGIRequest' object has no attribute 'new_count'"}
[19/Oct/2015 09:36:32] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:34] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'0']}>
[19/Oct/2015 09:36:34] ERROR [apps.hello.views:35] 'WSGIRequest' object has no attribute 'new_count'
[19/Oct/2015 09:36:34] INFO [apps.hello.views:36] check requests:{'result': "'WSGIRequest' object has no attribute 'new_count'"}
[19/Oct/2015 09:36:34] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:36] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'0']}>
[19/Oct/2015 09:36:36] ERROR [apps.hello.views:35] 'WSGIRequest' object has no attribute 'new_count'
[19/Oct/2015 09:36:36] INFO [apps.hello.views:36] check requests:{'result': "'WSGIRequest' object has no attribute 'new_count'"}
[19/Oct/2015 09:36:36] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:38] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'0']}>
[19/Oct/2015 09:36:38] ERROR [apps.hello.views:35] 'WSGIRequest' object has no attribute 'new_count'
[19/Oct/2015 09:36:38] INFO [apps.hello.views:36] check requests:{'result': "'WSGIRequest' object has no attribute 'new_count'"}
[19/Oct/2015 09:36:38] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:40] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'0']}>
[19/Oct/2015 09:36:40] ERROR [apps.hello.views:35] 'WSGIRequest' object has no attribute 'new_count'
[19/Oct/2015 09:36:40] INFO [apps.hello.views:36] check requests:{'result': "'WSGIRequest' object has no attribute 'new_count'"}
[19/Oct/2015 09:36:40] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:42] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:36:42] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:36:42] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:36:42] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:44] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:36:44] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:36:44] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:36:44] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:46] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:36:46] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:36:46] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:36:46] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:48] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:36:48] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:36:48] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:36:48] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:50] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:36:50] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:36:50] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:36:50] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:52] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:36:52] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:36:52] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:36:52] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:54] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:36:54] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:36:54] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:36:54] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:56] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:36:56] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:36:56] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:36:56] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:36:58] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:36:58] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:36:58] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:36:58] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:00] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:00] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:00] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:00] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:02] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:02] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:02] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:02] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:04] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:04] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:04] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:04] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:06] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:06] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:06] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:06] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:09] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:09] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:09] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:09] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:11] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:11] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:11] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:11] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:13] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:13] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:13] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:13] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:15] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:15] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:15] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:15] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:17] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:17] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:17] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:17] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:19] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:19] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:19] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:19] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:21] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:21] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:21] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:21] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:23] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:23] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:23] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:23] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:25] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:25] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:25] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:25] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:27] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:27] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:27] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:27] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:29] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:29] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:29] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:29] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:31] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:31] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:31] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:31] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:33] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:33] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:33] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:33] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:35] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:35] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:35] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:35] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:37] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:37] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:37] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:37] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:39] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:39] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:39] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:39] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:41] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:41] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:41] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:41] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:43] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:43] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:43] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:43] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:45] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:45] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:45] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:45] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:47] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:47] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:47] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:47] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:49] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:49] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:49] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:49] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:51] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:51] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:51] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:51] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:53] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:53] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:53] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:53] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:55] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:55] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:55] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:55] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:57] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:57] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:57] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:57] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:37:59] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:37:59] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:37:59] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:37:59] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:01] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:01] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:01] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:01] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:03] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:03] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:03] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:03] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:05] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:05] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:05] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:05] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:07] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:07] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:07] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:07] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:09] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:09] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:09] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:09] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:11] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:11] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:11] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:11] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:13] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:13] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:13] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:13] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:15] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:15] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:15] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:15] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:17] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:17] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:17] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:17] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:19] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:19] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:19] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:19] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:21] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:21] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:21] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:21] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:23] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:23] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:23] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:23] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:25] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:25] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:25] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:25] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:27] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:27] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:27] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:27] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:29] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:29] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:29] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:29] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:31] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:31] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:31] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:31] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:33] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:33] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:33] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:33] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:35] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:35] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:35] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:35] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:37] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:37] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:37] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:37] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:39] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:39] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:39] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:39] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:41] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:41] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:41] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:41] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:43] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:43] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:43] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:43] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:45] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:45] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:45] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:45] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:47] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:47] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:47] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:47] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:49] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:49] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:49] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:49] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:51] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:51] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:51] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:51] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:53] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:53] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:53] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:53] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:55] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:55] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:55] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:55] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:57] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:57] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:57] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:57] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:38:59] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:38:59] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:38:59] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:38:59] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:01] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:01] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:01] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:01] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:03] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:03] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:03] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:03] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:05] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:05] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:05] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:05] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:07] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:07] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:07] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:07] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:09] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:09] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:09] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:09] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:11] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:11] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:11] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:11] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:13] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:13] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:13] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:13] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:15] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:15] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:15] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:15] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:17] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:17] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:17] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:17] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:19] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:19] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:19] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:19] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:21] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:21] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:21] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:21] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:23] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:23] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:23] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:23] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:25] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:25] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:25] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:25] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:27] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:27] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:27] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:27] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:29] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:29] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:29] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:29] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:31] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:31] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:31] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:31] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:33] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:33] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:33] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:33] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:35] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:35] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:35] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:35] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:37] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:37] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:37] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:37] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:39] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:39] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:39] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:39] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:41] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:41] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:41] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:41] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:43] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:43] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:43] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:43] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:45] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:45] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:45] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:45] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:47] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:47] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:47] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:47] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:49] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:49] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:49] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:49] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:51] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:51] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:51] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:51] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:53] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:53] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:53] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:53] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:55] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:55] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:55] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:55] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:57] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:57] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:57] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:57] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:39:59] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:39:59] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:39:59] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:39:59] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:01] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:01] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:01] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:01] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:03] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:03] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:03] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:03] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:05] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:05] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:05] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:05] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:07] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:07] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:07] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:07] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:09] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:09] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:09] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:09] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:11] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:11] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:11] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:11] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:13] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:13] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:13] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:13] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:15] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:15] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:15] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:15] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:17] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:17] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:17] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:17] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:19] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:19] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:19] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:19] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:21] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:21] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:21] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:21] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:23] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:23] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:23] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:23] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:25] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:25] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:25] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:25] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:27] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:27] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:27] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:27] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:29] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:29] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:29] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:29] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:31] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:31] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:31] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:31] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:33] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:33] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:33] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:33] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:35] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:35] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:35] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:35] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:37] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:37] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:37] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:37] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:39] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:39] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:39] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:39] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:41] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:41] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:41] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:41] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:43] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:43] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:43] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:43] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:45] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:45] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:45] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:45] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:47] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:47] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:47] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:47] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:49] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:49] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:49] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:49] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:51] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:51] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:51] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:51] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:53] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:53] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:53] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:53] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:55] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:55] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:55] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:55] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:57] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:57] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:57] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:57] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:40:59] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:40:59] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:40:59] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:40:59] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:01] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:01] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:01] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:01] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:03] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:03] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:03] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:03] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:05] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:05] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:05] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:05] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:07] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:07] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:07] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:07] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:09] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:09] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:09] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:09] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:11] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:11] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:11] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:11] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:13] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:13] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:13] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:13] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:15] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:15] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:15] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:15] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:17] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:17] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:17] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:17] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:19] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:19] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:19] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:19] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:21] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:21] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:21] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:21] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:25] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'NaN']}>
[19/Oct/2015 09:41:25] ERROR [apps.hello.views:35] invalid literal for int() with base 10: 'NaN'
[19/Oct/2015 09:41:25] INFO [apps.hello.views:36] check requests:{'result': "invalid literal for int() with base 10: 'NaN'"}
[19/Oct/2015 09:41:25] ERROR [django.request:224] Internal Server Error: /requests/
Traceback (most recent call last):
  File "/home/ola/projects/FortyTwoTest/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ola/projects/FortyTwoTest/apps/hello/views.py", line 38, in req
    'delta_list': delta_list,
UnboundLocalError: local variable 'delta_list' referenced before assignment
[19/Oct/2015 09:41:26] INFO [apps.hello.views:26] <QueryDict: {}>
[19/Oct/2015 09:41:29] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'2']}>
[19/Oct/2015 09:41:29] INFO [apps.hello.views:36] check requests:{'result': 1}
[19/Oct/2015 09:41:31] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'2']}>
[19/Oct/2015 09:41:31] INFO [apps.hello.views:36] check requests:{'result': 2}
[19/Oct/2015 09:41:33] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'2']}>
[19/Oct/2015 09:41:33] INFO [apps.hello.views:36] check requests:{'result': 3}
[19/Oct/2015 09:41:36] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:36] INFO [apps.hello.views:36] check requests:{'result': 2}
[19/Oct/2015 09:41:38] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:38] INFO [apps.hello.views:36] check requests:{'result': 3}
[19/Oct/2015 09:41:39] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:39] INFO [apps.hello.views:36] check requests:{'result': 4}
[19/Oct/2015 09:41:41] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:41] INFO [apps.hello.views:36] check requests:{'result': 5}
[19/Oct/2015 09:41:43] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:43] INFO [apps.hello.views:36] check requests:{'result': 6}
[19/Oct/2015 09:41:45] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:45] INFO [apps.hello.views:36] check requests:{'result': 7}
[19/Oct/2015 09:41:47] INFO [apps.hello.views:26] <QueryDict: {}>
[19/Oct/2015 09:41:47] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'15']}>
[19/Oct/2015 09:41:47] INFO [apps.hello.views:36] check requests:{'result': 1}
[19/Oct/2015 09:41:47] INFO [apps.hello.views:26] <QueryDict: {}>
[19/Oct/2015 09:41:48] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:48] INFO [apps.hello.views:36] check requests:{'result': 8}
[19/Oct/2015 09:41:49] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:49] INFO [apps.hello.views:36] check requests:{'result': 9}
[19/Oct/2015 09:41:51] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:51] INFO [apps.hello.views:36] check requests:{'result': 10}
[19/Oct/2015 09:41:53] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:53] INFO [apps.hello.views:36] check requests:{'result': 11}
[19/Oct/2015 09:41:55] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:55] INFO [apps.hello.views:36] check requests:{'result': 12}
[19/Oct/2015 09:41:57] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:57] INFO [apps.hello.views:36] check requests:{'result': 13}
[19/Oct/2015 09:41:59] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:41:59] INFO [apps.hello.views:36] check requests:{'result': 14}
[19/Oct/2015 09:42:03] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:42:03] INFO [apps.hello.views:36] check requests:{'result': 15}
[19/Oct/2015 09:42:05] INFO [apps.hello.views:26] <QueryDict: {}>
[19/Oct/2015 09:42:05] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'15']}>
[19/Oct/2015 09:42:05] INFO [apps.hello.views:36] check requests:{'result': 1}
[19/Oct/2015 09:42:05] INFO [apps.hello.views:26] <QueryDict: {}>
[19/Oct/2015 09:42:05] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:42:05] INFO [apps.hello.views:36] check requests:{'result': 16}
[19/Oct/2015 09:42:07] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:42:07] INFO [apps.hello.views:36] check requests:{'result': 17}
[19/Oct/2015 09:42:09] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'4']}>
[19/Oct/2015 09:42:09] INFO [apps.hello.views:36] check requests:{'result': 18}
[19/Oct/2015 09:42:11] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'22']}>
[19/Oct/2015 09:42:11] INFO [apps.hello.views:36] check requests:{'result': 1}
[19/Oct/2015 09:42:13] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:13] INFO [apps.hello.views:36] check requests:{'result': 1}
[19/Oct/2015 09:42:15] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:15] INFO [apps.hello.views:36] check requests:{'result': 2}
[19/Oct/2015 09:42:18] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:18] INFO [apps.hello.views:36] check requests:{'result': 3}
[19/Oct/2015 09:42:21] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:21] INFO [apps.hello.views:36] check requests:{'result': 4}
[19/Oct/2015 09:42:22] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:22] INFO [apps.hello.views:36] check requests:{'result': 5}
[19/Oct/2015 09:42:24] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:24] INFO [apps.hello.views:36] check requests:{'result': 6}
[19/Oct/2015 09:42:26] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:26] INFO [apps.hello.views:36] check requests:{'result': 7}
[19/Oct/2015 09:42:29] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:29] INFO [apps.hello.views:36] check requests:{'result': 8}
[19/Oct/2015 09:42:30] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:30] INFO [apps.hello.views:36] check requests:{'result': 9}
[19/Oct/2015 09:42:32] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:32] INFO [apps.hello.views:36] check requests:{'result': 10}
[19/Oct/2015 09:42:34] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:34] INFO [apps.hello.views:36] check requests:{'result': 11}
[19/Oct/2015 09:42:36] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:36] INFO [apps.hello.views:36] check requests:{'result': 12}
[19/Oct/2015 09:42:38] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:38] INFO [apps.hello.views:36] check requests:{'result': 13}
[19/Oct/2015 09:42:40] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:40] INFO [apps.hello.views:36] check requests:{'result': 14}
[19/Oct/2015 09:42:42] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:42] INFO [apps.hello.views:36] check requests:{'result': 15}
[19/Oct/2015 09:42:44] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:44] INFO [apps.hello.views:36] check requests:{'result': 16}
[19/Oct/2015 09:42:46] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:46] INFO [apps.hello.views:36] check requests:{'result': 17}
[19/Oct/2015 09:42:48] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:48] INFO [apps.hello.views:36] check requests:{'result': 18}
[19/Oct/2015 09:42:51] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:51] INFO [apps.hello.views:36] check requests:{'result': 19}
[19/Oct/2015 09:42:53] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:53] INFO [apps.hello.views:36] check requests:{'result': 20}
[19/Oct/2015 09:42:54] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:54] INFO [apps.hello.views:36] check requests:{'result': 21}
[19/Oct/2015 09:42:56] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:56] INFO [apps.hello.views:36] check requests:{'result': 22}
[19/Oct/2015 09:42:58] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:42:58] INFO [apps.hello.views:36] check requests:{'result': 23}
[19/Oct/2015 09:43:01] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'23']}>
[19/Oct/2015 09:43:01] INFO [apps.hello.views:36] check requests:{'result': 24}
[19/Oct/2015 09:43:02] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'46']}>
[19/Oct/2015 09:43:02] INFO [apps.hello.views:36] check requests:{'result': 2}
[19/Oct/2015 09:44:54] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'50']}>
[19/Oct/2015 09:44:54] INFO [apps.hello.views:36] check requests:{'result': -1}
[19/Oct/2015 09:44:55] INFO [apps.hello.views:26] <QueryDict: {}>
[19/Oct/2015 09:44:55] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'52']}>
[19/Oct/2015 09:44:55] INFO [apps.hello.views:36] check requests:{'result': -1}
[19/Oct/2015 09:44:58] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'50']}>
[19/Oct/2015 09:44:58] INFO [apps.hello.views:36] check requests:{'result': 2}
[19/Oct/2015 09:45:00] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'50']}>
[19/Oct/2015 09:45:00] INFO [apps.hello.views:36] check requests:{'result': 3}
[19/Oct/2015 09:45:02] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'50']}>
[19/Oct/2015 09:45:02] INFO [apps.hello.views:36] check requests:{'result': 4}
[19/Oct/2015 09:45:04] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'50']}>
[19/Oct/2015 09:45:04] INFO [apps.hello.views:36] check requests:{'result': 5}
[19/Oct/2015 09:45:06] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'50']}>
[19/Oct/2015 09:45:06] INFO [apps.hello.views:36] check requests:{'result': 6}
[19/Oct/2015 09:45:08] INFO [apps.hello.views:26] <QueryDict: {u'request_old_count': [u'56']}>
[19/Oct/2015 09:45:08] INFO [apps.hello.views:36] check requests:{'result': 1}
